### ISSUE TITLE
website now block ip

### ISSUE THREAD

**Issue by satisfywithmylife** [Flamingo-at/ethermail#1]
as title

**Comment by Flamingo-at** [comment]
Can you elaborate on the problem? Since my script is working steadily at the moment.

**Comment by Flamingo-at** [comment]
> as title

Can you elaborate on the problem? Since my script is working steadily at the moment and ip is not blocked.

**Comment by satisfywithmylife** [comment]
>It's strange that my IP was banned yesterday, and the auth interface also added a new csrf parameter. Today it's gone again. It seems that the code has been rolled back, and the IP ban now is lift

**Comment by Flamingo-at** [comment]
Ran into the problem you mentioned today, after making a lot of referrals yesterday. I recommend putting a delay and a small number of threads. Enough to change ip in any way and access to the site will be open. Fortunately the account was not blocked. Be careful.
![image](https://user-images.githubusercontent.com/119711235/222957933-4344d874-8147-40fd-82d2-bafe829af45a.png)

**Comment by satisfywithmylife** [comment]
> Ran into the problem you mentioned today, after making a lot of referrals yesterday. I recommend putting a delay and a small number of threads. Enough to change ip in any way and access to the site will be open. Fortunately the account was not blocked. Be careful. ![image](https://user-images.githubusercontent.com/119711235/222957933-4344d874-8147-40fd-82d2-bafe829af45a.png)

i will try use some proxies，thanks

**Comment by satisfywithmylife** [comment]
its seems like no referer award a again，maybe the website change rules

**Comment by Flamingo-at** [comment]
> its seems like no referer award a again，maybe the website change rules

Does it write an error in the bot itself or do they not add points on the site? If the latter, then sometimes there is a delay for hours. Since yesterday, only today, points have been credited to me.
